# Site settings
title: ScalaMock
description: "Native scala mocking"
baseurl: "" #important: start with /
url: "https://scalamock.org"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
kramdown:
    input: GFM 
    enable_coderay: false # it does not support scala syntax highlighting

collections:
  user_guide:
      output: true
      collectionTitle: "User Guide"
  quick_start:
      output: true
      collectionTitle: "Quick Start"
